name: Release Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          arch: win64_mingw

      - name: Build
        shell: cmd
        run: |
          set PATH=%QT_ROOT_DIR%\Tools\mingw1310_64\bin;%PATH%
          qmake ExtSorter.pro CONFIG+=release
          mingw32-make -j4

      - name: Deploy Qt
        shell: cmd
        run: |
          windeployqt release\ExtSorter.exe

      - name: Remove unnecessary Qt plugin folders
        shell: pwsh
        run: |
          $deployDir = "release"

          Get-ChildItem $deployDir -Directory | ForEach-Object {
            if ($_.Name -notin @(
              "iconengines",
              "imageformats",
              "platforms",
              "styles"
            )) {
              Remove-Item $_.FullName -Recurse -Force
            }
          }

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path release\* `
            -DestinationPath "ExtSorter-${{ github.ref_name }}.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ExtSorter ${{ github.ref_name }}
          body: |
            ## Nuevo en esta versión
          files: ExtSorter-${{ github.ref_name }}.zip