name: Release Windows

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          arch: win64_mingw
          tools: tools_mingw1310

      - name: Debug environment
        shell: cmd
        run: |
          where qmake
          where g++
          qmake -v
          g++ --version
          
      - name: Build
        shell: cmd
        run: |
          set PATH=%QT_ROOT_DIR%\Tools\mingw1310_64\bin;%PATH%
          qmake ExtSorter.pro CONFIG+=release
          mingw32-make -j4

      - name: Deploy Qt
        shell: cmd
        run: |
          windeployqt release\ExtSorter.exe

      - name: Remove unnecessary files
        shell: pwsh
        run: |
          $deployDir = "release"

          $allowedFolders = @(
            "iconengines",
            "imageformats",
            "platforms",
            "styles"
          )

          $allowedFiles = @(
            "ExtSorter.exe",
            "Qt6Core.dll",
            "Qt6Gui.dll",
            "Qt6Widgets.dll",
            "D3Dcompiler_47.dll",
            "opengl32sw.dll",
            "libgcc_s_seh-1.dll",
            "libstdc++-6.dll",
            "libwinpthread-1.dll"
          )

          Get-ChildItem $deployDir | ForEach-Object {

            if ($_.PSIsContainer) {
              if ($_.Name -notin $allowedFolders) {
                Remove-Item $_.FullName -Recurse -Force
              }
            }
            else {
              if ($_.Name -notin $allowedFiles) {
                Remove-Item $_.FullName -Force
              }
            }
          }

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path release\* `
            -DestinationPath "ExtSorter-${{ github.ref_name }}.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ExtSorter ${{ github.ref_name }}
          body: |
            ## Nuevo en esta versión
          files: ExtSorter-${{ github.ref_name }}.zip